name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout master
      uses: actions/checkout@v3
    - name: Checkout submodules
      uses: slack-libpurple/git-checkout-submodule-action@master
      with:
        remote: true
      
    - name: Install dependencies
      run: make
      
    - name: Run check
      run: make check
      
    - name: Run distcheck
      run: make distcheck
